### ISSUE TITLE
Request for Supplemental Materials

### ISSUE THREAD

**Issue by gdut-zqr** [MICS-Lab/novae#6]
Hi Quentin,

Thank you for your excellent work on Novae. I noticed that the supplemental materials aren’t available on bioRxiv. If you could share them, I would be very grateful.

Thank you!

**Comment by quentinblampey** [comment]
Hi @gdut-zqr, sorry for the delay (I didn't receive a notification...)

Of course, here are the supplementals: https://drive.google.com/file/d/1-yDK0hw6I19yviwLf496ADm-lV4RlbOr/view?usp=drive_link 

Let me know if you need extra information! (closing the issue for now, but feel free to re-open)
