### ISSUE TITLE
Problems with novae.plot.domains function on Cosmx data

### ISSUE THREAD

**Issue by paolamaragno** [MICS-Lab/novae#8]
Hi,

I am analyising Cosmx spatial transcriptomics data. In particular I have a single slide containing pieces of tissue from different patients. From each single patient 2/3 FOVs were acquired.
Consequently I have a single AnnData object containing two columns that specify, for each cell, the patient and the FOV to which the cell belongs.
The structure of my AnnData object is the following:
<img width="1012" alt="image" src="https://github.com/user-attachments/assets/aa514940-5f66-4ec2-80b5-339f0f070748">

My first doubt is whether I have to consider my data as multi-slide/multi-panel having multiple fovs (19 in total) using the command model.compute_representations(adata, zero_shot=True, slide_key="fov"), that indeed worked.

For the moment I considered my data as single-slide and I run the following commands without problems:
model = novae.Novae.from_pretrained("MICS-Lab/novae-human-0")
novae.utils.spatial_neighbors(adata, slide_key='fov',technology='cosmx') 
model.compute_representations(adata, zero_shot=True)
model.assign_domains(adata)

When I try to plot the domains using novae.plot.domains(adata) command, I got this error:
<img width="1016" alt="image" src="https://github.com/user-attachments/assets/8ff589e4-20d9-41fe-8a57-ad4da6f8d7a9">

This is the structure of adata.uns['spatial']:
<img width="415" alt="image" src="https://github.com/user-attachments/assets/4884340e-cf90-47b5-8344-1a28539f1e28">

In order to visualize domains by FOV eventually I used this command and it worked:
sq.pl.spatial_segment(
    adata=adata,
    color='novae_domains_7',
    library_key="fov",
    seg_cell_id="cell_ID",
    seg_outline=True,
    img=False,
    scalebar_dx=1.0,
    title= t,
    scalebar_kwargs={"scale_loc": "bottom", "location": "lower right"},
)

But, is there a way to use novae.plot.domains(adata) on my data?

Thank you very much,
Paola Maragno

**Comment by quentinblampey** [comment]
I pushed a fix in `main`. If you confirm that it fixed your issue, I'll release it in the newt version :)

**Comment by paolamaragno** [comment]
Hi @quentinblampey,

Thank you for the reply!

To create my AnnData object I used the following command:
adata = sq.read.nanostring(
    path=sample_dir,
    counts_file="R5941_ColonTMA_exprMat_file_CD.csv",
    meta_file="R5941_ColonTMA_metadata_file_CD.csv",
    fov_file="R5941_ColonTMA_fov_positions_file_CD.csv",
)

I tried using library_id=None and indeed it worked, thanks!! The only problem is that in this way I see the whole slide, with all the fovs together:
![image](https://github.com/user-attachments/assets/74fe58a7-d0cd-4180-b2e4-5f9cafb547ea)

I tried to subsample the entire AnnData object extracting only the cells from fov 21, and then, using the same command on the subset, I obtained this:
![image](https://github.com/user-attachments/assets/31059c01-75e5-485f-aa82-234dc5823f3f)
That actually is exactly the same I obtained using sq.pl.spatial_segment function that allows me to plot all the fovs, one close to the other, without having to create all the subsets. 

I don't know if it is possible to add a parameter to novae.plot.domains to plot all the fovs separately.

Thank you again!!
Paola

**Comment by paolamaragno** [comment]
Yes it worked!! Thank you very much!

**Comment by quentinblampey** [comment]
Nice!! Good to hear.

Don't hesitate to open a new issue if you have any bug/question/request.

I'm closing the issue. In the next release (i.e., `novae==0.1.1`), you'll be able to remove the `library_id=None` argument from the `novae.plot.domains` function!

**Comment by quentinblampey** [comment]
Hey @paolamaragno,

I released `novae==0.2.0`, which fixes your issue. Still, not that I changed other things, so please refer to the [new tutorial](https://mics-lab.github.io/novae/tutorials/main_usage/) version. The main difference is that I now force the user to run [`novae.utils.spatial_neighbors`](https://mics-lab.github.io/novae/api/utils/#novae.utils.spatial_neighbors), because I want to ensure that the user is doing what he thinks he is doing. Novae will get more stable and we'll see less breaking changes like this in the future!
